language: python

dist: xenial

cache:
  pip: true
  cargo: true

matrix:
  include:
    - python: "2.7"
      env: FEATURES=python2
    - python: "3.5"
      env: FEATURES=python3
    - python: "3.6"
      env: FEATURES=python3
    - python: "3.7"
      env: FEATURES=python3

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - source ./ci/travis/setup.sh

install:
  - pip install setuptools-rust pytest pytest-benchmark tox

script:
  - ./ci/travis/test.sh

deploy:
# FIXME: kcov seems to be broken
#  - provider: script
#    skip_cleanup: true
#    script: ./ci/travis/cover.sh
#    on:
#      branch: master
#      condition: $TRAVIS_EVENT_TYPE != "cron"
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/guide.sh
    on:
      branch: master
      repo: PyO3/pyo3
      python: 3.6
      condition: $TRAVIS_EVENT_TYPE != "cron"
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/guide.sh
    on:
      tags: true
      repo: PyO3/pyo3
      python: 3.6

notifications:
  email: false
