[package]
name = "pyo3"
version = "0.5.0"
description = "Bindings to Python interpreter"
authors = ["PyO3 Project and Contributors <https://github.com/PyO3>"]
readme = "README.md"
keywords = ["pyo3", "python", "cpython", "ffi"]
homepage = "https://github.com/pyo3/pyo3"
repository = "https://github.com/pyo3/pyo3"
documentation = "https://docs.rs/crate/pyo3/"
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0"
exclude = ["/.gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[badges]
travis-ci = { repository = "PyO3/pyo3", branch = "master" }
appveyor = { repository = "fafhrd91/pyo3" }
codecov = { repository = "PyO3/pyo3", branch = "master", service = "github" }

[dependencies]
libc = "0.2.43"
num-traits = "0.2.6"
spin = "0.4.9"
pyo3cls = { path = "pyo3cls", version = "=0.5.0" }
num-complex = { version = "0.2.1", optional = true }
mashup = "0.1.9"

[build-dependencies]
version_check = "0.1.5"
pretty_assertions = "0.5.1"
pyo3-build-utils = {version = "*", path="pyo3build"}
regex = "1.0.5"

[dev-dependencies]
pretty_assertions = "0.5.1"
docmatic = "^0.1.2"
assert_approx_eq = "1.0.0"
indoc = "0.3.1"

[features]
default = []

# Use this feature when building python2 binding.
# python2 = []

# Use this feature when building python3 binding.
python3 = []

# Use this feature when building pypy binding.
# pypy = []
# Use this feature when building an extension module.
# It tells the linker to keep the python symbols unresolved,
# so that the module can also be used with statically linked python interpreters.
extension-module = []

# The stable cpython abi as defined in PEP 384. Currently broken with
# many compilation errors. Pull Requests working towards fixing that
# are welcome.
# abi3 = []

[workspace]
members = [
    "pyo3cls",
    "pyo3-derive-backend",
    "examples/*"
]
